### ISSUE TITLE
No marker peaks for three cell types in `atacRef_TME`

### ISSUE THREAD

**Issue by eafyounian** [GfellerLab/EPIC-ATAC#3]
Hello,

The `atacRef_TME` object seems to lack marker peaks for **endothelial**, **fibroblast**, and **macrophage** cell types. Is this expected?

Here is how I have checked this:

```r
# devtools::install_github("GfellerLab/EPIC-ATAC", build_vignettes=TRUE)
library(EPICATAC)
markers_list <- atacRef_TME$markers

result_df <- data.frame(Chromosome = character(), Start = integer(), End = integer(), Subcomponent = character(), stringsAsFactors = FALSE)

for (subcomponent in names(markers_list)) {
  regions <- markers_list[[subcomponent]]
  
  split_regions <- strsplit(regions, "-")
  chrom <- sapply(split_regions, `[`, 1)
  start <- as.integer(sapply(split_regions, `[`, 2))
  end <- as.integer(sapply(split_regions, `[`, 3))
  
  temp_df <- data.frame(Chromosome = chrom, Start = start, End = end, Subcomponent = subcomponent, stringsAsFactors = FALSE)

  result_df <- rbind(result_df, temp_df)
}

write.table(result_df, "atacRef_TME_markers.bed", sep = "\t", row.names = FALSE, col.names = FALSE, quote = FALSE)
```

`markerPeaks.saf` was downloaded from [here](https://raw.githubusercontent.com/GfellerLab/EPIC-ATAC/master/inst/extdata/markerPeaks.saf).

```bash
bedtools intersect -u -a <(bedtools sort -i atacRef_TME_markers.bed) -b <(tail -n+2 markerPeaks.saf | cut -f2-4 | bedtools sort) | cut -f4 | sort | uniq -c
# 87 Bcells
# 64 CD4_Tcells
# 95 CD8_Tcells
# 95 DCs
# 48 Neutrophils
# 89 NK


cut -f4 atacRef_TME_markers.bed | sort | uniq -c
# 87 Bcells
# 64 CD4_Tcells
# 95 CD8_Tcells
# 95 DCs
# 48 Neutrophils
# 89 NK
# 91 Endothelial
# 59 Fibroblasts
# 88 Macrophages
```

Thank you in advance for consideration and response.

**Comment by aurelieGabriel** [comment]
Hello,

Thank you for raising this issue. I checked the `markerPeaks.saf` file and indeed, only the `atacRef_PBMC` markers were included in the file. For the immune cell types, the `atacRef_TME` markers are a subset of the `atacRef_PBMC` markers which explains why you could find the markers of some cell types.

I apologize for this mistake and have updated the SAF file available on GitHub to include all the markers (from both `atacRef_PBMC` and `atacRef_TME`).

Best wishes,
Aurélie

**Comment by eafyounian** [comment]
Dear Aurélie, thanks so much for your quick reply and the help.
